test: ci supercharge/redis 사용

diff --git a/.github/workflows/develop-ci.yml b/.github/workflows/develop-ci.yml
--- a/.github/workflows/develop-ci.yml
+++ b/.github/workflows/develop-ci.yml
@@ -15,30 +15,35 @@ jobs:
       checks: write
       pull-requests: write
 
-    services:
-      redis:
-        image: redis:latest # redis 이미지
-        ports:
-          - 6379:6379
-        options: >-
-          --name redis
-          --health-cmd "redis-cli ping || exit 1"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+#    services:
+#      redis:
+#        image: redis:latest # redis 이미지
+#        ports:
+#          - 6379:6379
+#        options: >-
+#          --name redis
+#          --hostname redis
+#          --health-cmd "redis-cli ping || exit 1"
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
 
     steps:
       # redis 띄워지는걸 기다리기
-      - name: Wait for Redis
-        run: |
-          for i in {1..10}; do
-            if redis-cli -h redis -p 6379 ping; then
-              echo "Redis is up!"
-              break
-            fi
-            echo "Waiting for Redis..."
-            sleep 3
-          done
+#      - name: Wait for Redis
+#        run: |
+#          for i in {1..10}; do
+#            if redis-cli -h redis -p 6379 ping; then
+#              echo "Redis is up!"
+#              break
+#            fi
+#            echo "Waiting for Redis..."
+#            sleep 3
+#          done
+      - name: set up redis
+        uses: supercharge/redis-github-action@1.7.0
+        with:
+          redis-version: 'latest'
 
       - name: checkout the code
         uses: actions/checkout@v4
